const countries = [
  ['AD', 'Andorra',	'Andorra'],
  ['AF', 'Afgana',	'Afganistán'],
  ['AG', 'Antigua', 'y Barbado	Antigua y Barbado'],
  ['AI', 'Anguila',	'Anguila'],
  ['AN', 'Albania',	'Albania'],
  ['AO', 'Angola',	'Angola'],
  ['AS', 'Ascensión',	'Ascensión'],
  ['AT', 'Argentina',	'Argentina'],
  ['AU', 'Australiana',	'Australia'],
  ['AW', 'Árabe',	'Arabia'],
  ['AX', 'Azores',	'Azores'],
  ['BB', 'Barbados',	'Barbados'],
  ['BD', 'Bangladesh',	'Bangladesh'],
  ['BE', 'Belga',	'Bélgica'],
  ['BF', 'Burkina',	'Burkina'],
  ['BG', 'Búlgara',	'Bulgaria'],
  ['BH', 'Bahrein',	'Bahrein'],
  ['BI', 'Burundi',	'Burundi'],
  ['BJ', 'Benin',	'Benin'],
  ['BK', 'Birmania',	'Birmania'],
  ['BM', 'Bután',	'Bután'],
  ['BN', 'Brunei',	'Brunei'],
  ['BO', 'Boliviana',	'Bolivia'],
  ['BR', 'Brasileño',	'Brasil'],
  ['BS', 'Bahamas',	'Bahamas'],
  ['BU', 'Bermudas',	'Bermudas'],
  ['BW', 'Botswana',	'Botswana'],
  ['BX', 'Bosnia', 'Herzegovina	Bosnia Herzegovina'],
  ['BZ', 'Belice',	'Belice'],
  ['CB', 'Colombiana',	'Colombia'],
  ['CC', 'Córcega',	'Córcega'],
  ['CD', 'Chad',	'Chad'],
  ['CF', 'Rep. Central Africana', 'Rep. Central Africana'],
  ['CG', 'Congo',	'Congo'],
  ['CH', 'Liechtenstein',	'Liechtenstein'],
  ['CI', 'Islas Caimán',	'Islas Caimán'],
  ['CJ', 'Comoros',	'Comoros'],
  ['CL', 'Chilena',	'Chile'],
  ['CM', 'Camerunés',	'Camerún'],
  ['CN', 'Canadiense', 'Canadá'],
  ['CP', 'China',	'China(Pekín)'],
  ['CS', 'República Checa Eslovaca', 'República Checa Eslovaca'],
  ['CU', 'Cariacou', 'Cariacou'],
  ['CV', 'Cabo Verde', 'Cabo Verde'],
  ['CY', 'Chipre',	'Chipre'],
  ['DF', 'Austriaca',	'Austria'],
  ['DJ', 'Djibouti',	'Djibouti'],
  ['DK', 'Danés',	'Dinamarca'],
  ['DM', 'Dominicana',	'Dominicana'],
  ['DO', 'Dominicana',	'República Dominicana'],
  ['DW', 'Alemana',	'Alemania'],
  ['DZ', 'Argelia',	'Argelia'],
  ['EC', 'Ecuatoriana',	'Ecuador'],
  ['EG', 'Egipcia',	'Egipto'],
  ['EM', 'Timor Oriental', 'Timor Oriental'],
  ['ES', 'Española',	'España'],
  ['ET', 'Etiopia',	'Etiopia'],
  ['FA', 'Islas Falkland(Malvinas)', 'Islas Falkland(Malvinas)'],
  ['FE', 'Islas Faroe',	'Islas Faroe'],
  ['FI', 'Finlandia',	'Finlandia'],
  ['FJ', 'Fiji',	'Fiji'],
  ['FP', 'Polinesia',	'Polinesia'],
  ['FR', 'Francesa',	'Francia'],
  ['GB', 'Gabón',	'Gabón'],
  ['GD', 'Granada',	'Granada'],
  ['GE', 'Groenlandia',	'Groenlandia'],
  ['GF', 'Guayana Francesa', 'Guayana Francesa'],
  ['GH', 'Ghana',	'Ghana'],
  ['GI', 'Gibraltar',	'Gibraltar'],
  ['GM', 'Gambia',	'Gambia'],
  ['GN', 'Guinea',	'Guinea'],
  ['GP', 'Guadalupe',	'Guadalupe'],
  ['GQ', 'Guinea Ecuatorial',	'Guinea Ecuatorial'],
  ['GR', 'Griega',	'Grecia'],
  ['GT', 'Guatemalteca',	'Guatemala'],
  ['GW', 'Guinea Bissau',	'Guinea Bissau'],
  ['GX', 'República De Georgia',	'República De Georgia'],
  ['GY', 'Guyana',	'Guyana'],
  ['HA', 'Haitiana',	'Haití'],
  ['HK', 'Hong Kong',	'Hong Kong'],
  ['HN', 'Hondureña',	'Honduras'],
  ['HR', 'Cubano',	'Cuba'],
  ['HU', 'Húngara',	'Húngara'],
  ['HX', 'Croata',	'Croacia'],
  ['IB', 'India',	'India'],
  ['IC', 'Costa De Marfil', 'Costa De Marfil'],
  ['IE', 'Irlandesa',	'Irlandesa'],
  ['IF', 'Indonesia',	'Indonesia'],
  ['IG', 'Israelí',	'Israelí'],
  ['IQ', 'Iraquí',	'Iraquí'],
  ['IR', 'Iraní',	'Iraní'],
  ['IS', 'Islandia',	'Islandia'],
  ['IT', 'Italiano',	'Italiano'],
  ['JM', 'Jamaicano',	'Jamaicano'],
  ['JO', 'Jordano',	'Jordano'],
  ['JP', 'Japonesa',	'Japonesa'],
  ['KA', 'Kampuchea',	'Kampuchea'],
  ['KE', 'Kenya',	'Kenya'],
  ['KI', 'Kiribati',	'Kiribati'],
  ['KN', 'San Cristóbal De Neváis',	'San Cristóbal De Neváis'],
  ['KR', 'Corea Del Sur',	'Corea Del Sur'],
  ['KW', 'Kuwait',	'Kuwait'],
  ['KX', 'Corea Del Norte',	'Corea Del Norte'],
  ['LB', 'Libanes',	'Libanes'],
  ['LC', 'Santa Lucia',	'Santa Lucia'],
  ['LE', 'Islas De Sotavento',	'Islas De Sotavento'],
  ['LK', 'Sri Lanka',	'Sri Lanka'],
  ['LO', 'Laos',	'Laos'],
  ['LR', 'Liberia',	'Liberia'],
  ['LS', 'Lesotho',	'Lesotho'],
  ['LT', 'Lituania',	'Lituania'],
  ['LU', 'Luxemburgo',	'Luxemburgo'],
  ['LV', 'Libia',	'Libia'],
  ['LX', 'Letonia',	'Letonia'],
  ['MC', 'Mongolia',	'Mongolia'],
  ['MD', 'Madeira',	'Madeira'],
  ['MG', 'Madagascar',	'Madagascar'],
  ['MH', 'Macedonia',	'Macedonia'],
  ['MJ', 'Macao',	'Macao'],
  ['MK', 'Montserrat',	'Montserrat'],
  ['ML', 'Mali',	'Mali'],
  ['MM', 'Montenegro',	'Montenegro'],
  ['MP', 'Sao Tome y Principado',	'Sao Tome y Principado'],
  ['MQ', 'Martinico',	'Martinico'],
  ['MR', 'Mauritania',	'Mauritania'],
  ['MT', 'Malta',	'Malta'],
  ['MU', 'Mauricio',	'Mauricio'],
  ['MV', 'Maldivas',	'Maldivas'],
  ['MW', 'Malawi',	'Malawi'],
  ['MX', 'Mexicana',	'México'],
  ['MY', 'Malasia',	'Malasia'],
  ['MZ', 'Mozambique',	'Mozambique'],
  ['NA', 'Nauru',	'Nauru'],
  ['ND', 'No', 'Definido	No Definido'],
  ['NI', 'Nicaragua',	'Nicaragua'],
  ['NL', 'Holandesa',	'Holanda'],
  ['NN', 'Antillas Holandesas',	'Antillas Holandesas'],
  ['NO', 'Noruega',	'Noruega'],
  ['NP', 'Nepal',	'Nepal'],
  ['NR', 'Nigeriano',	'Nigeria'],
  ['NW', 'Nueva Caledonia',	'Nueva Caledonia'],
  ['NZ', 'Nueva Zelandia', 'Nueva Zelandia'],
  ['OA', 'Katar',	'Katar'],
  ['OM', 'Omán',	'Omán'],
  ['PG', 'Papúa Nueva Guinea', 'Papúa Nueva Guinea'],
  ['PH', 'Filipinas',	'Filipinas'],
  ['PK', 'Pakistán',	'Pakistán'],
  ['PL', 'Polaco',	'Polonia'],
  ['PM', 'Panameño',	'Panamá'],
  ['PS', 'Islas Pitcairn', 'Islas Pitcairn'],
  ['PT', 'Portugués',	'Portugal'],
  ['PU', 'Peruana',	'Perú'],
  ['PY', 'Paraguayo',	'Paraguay'],
  ['RC', 'Marroquí',	'Marruecos'],
  ['RE', 'Islas Reunión',	'Islas Reunión'],
  ['RO', 'Rumana',	'Rumania'],
  ['RU', 'Rusa',	'Rusia'],
  ['RW', 'Ruanda',	'Ruanda'],
  ['SA', 'Saudí Árabe',	'Arabia Saudita'],
  ['SB', 'Sudan',	'Sudan'],
  ['SE', 'Sueco',	'Suecia'],
  ['SF', 'San Vencen y Las Granadas',	'San Vencen y Las Granadas'],
  ['SH', 'Santa Helena', 'Santa Helena'],
  ['SI', 'Islas Salmon', 'Islas Salmon'],
  ['SN', 'Senegal',	'Senegal'],
  ['SO', 'Somalia',	'Somalia'],
  ['SP', 'San Pierre y Miquelón',	'San Pierre y Miquelón'],
  ['SR', 'Surinam',	'Surinam'],
  ['SS', 'San Kitts',	'San Kitts'],
  ['ST', 'Islas Santa Cruz', 'Islas Santa Cruz'],
  ['SU', 'Estonia',	'Estonia'],
  ['SV', 'Salvadoreña',	'El Salvador'],
  ['SW', 'Suiza',	'Suiza'],
  ['SX', 'Serbia',	'Serbia'],
  ['SY', 'Siria',	'Siria'],
  ['SZ', 'Swazilandia',	'Swazilandia'],
  ['TA', 'Tonga',	'Tonga'],
  ['TC', 'Turcos e Islas Caicos',	'Turcos e Islas Caicos'],
  ['TD', 'Tristán De Cunha', 'Tristán De Cunha'],
  ['TG', 'Togo',	'Togo'],
  ['TH', 'Tailandia',	'Tailandia'],
  ['TR', 'Turca',	'Turquía'],
  ['TT', 'Trinidad y Tobago',	'Trinidad y Tobago'],
  ['TU', 'Túnez',	'Túnez'],
  ['TV', 'Tuvala',	'Tuvala'],
  ['TW', 'Taiwán',	'Taiwán'],
  ['TZ', 'Tanzania',	'Tanzania'],
  ['UA', 'Ucraniano',	'Ucrania'],
  ['UG', 'Uganda',	'Uganda'],
  ['UK', 'Reino Unido', 'Reino Unido'],
  ['UM', 'Árabe',	'Emiratos Árabes Unidos'],
  ['US', 'Estadounidense',	'Estados Unidos'],
  ['UY', 'Uruguayo',	'Uruguay'],
  ['VC', 'Ciudad Del Vaticano', 'Ciudad Del Vaticano'],
  ['VE', 'Venezolana',	'Venezuela'],
  ['VG', 'Islas Vírgenes Inglesas',	'Islas Vírgenes Inglesas'],
  ['VN', 'Vietnami',	'Vietnam'],
  ['VU', 'Vanuatu',	'Vanuatu'],
  ['WS', 'Samoa Oeste', 'Samoa Oeste'],
  ['WT', 'Gales / Isla Futura',	'Gales / Isla Futura'],
  ['XN', 'Eslovenia',	'Eslovenia'],
  ['YE', 'Yemen(Del Sur)', 'Yemen(Del Sur)'],
  ['YS', 'Yemen(Del Norte)', 'Yemen(Del Norte)'],
  ['ZA', 'Sudafricana',	'África Del Sur'],
  ['ZM', 'Zambia',	'Zambia'],
  ['ZR', 'Zaire',	'Zaire'],
  ['ZW', 'Zimbabwe',	'Zimbabwe'],
];

export default countries;
