const states = [
  ['AGS', 'AGUASCALIENTES'],
  ['BC', 'BAJA CALIFORNIA NORTE'],
  ['BCS', 'BAJA CALIFORNIA SUR'],
  ['CAMP', 'CAMPECHE'],
  ['CDMX', 'CIUDAD DE MÉXICO'],
  ['CHIS', 'CHIAPAS'],
  ['CHIH', 'CHIHUAHUA'],
  ['COAH', 'COHAHUILA'],
  ['COL', 'COLIMA'],
  ['DF', 'DISTRITO FEDERAL'],
  ['DGO', 'DURANGO'],
  ['GTO', 'GUANAJUATO'],
  ['GRO', 'GUERRERO'],
  ['HGO', 'HIDALGO'],
  ['JAL', 'JALISCO'],
  ['MEX', 'MÉXICO'],
  ['MICH', 'MICHOCÁN'],
  ['MOR', 'MORELOS'],
  ['NAY', 'NAYARIT'],
  ['NL', 'NUEVO LEÓN'],
  ['OAX', 'OXACA'],
  ['PUE', 'PUEBLA'],
  ['QRO', 'QUERÉTARO'],
  ['QROO', 'QUINTANA ROO'],
  ['SLP', 'SAN LUIS POTOSÍ'],
  ['SIN', 'SINALOA'],
  ['SON', 'SONORA'],
  ['TAB', 'TABASCO'],
  ['TAMP', 'TAMAULIPAS'],
  ['TLAX', 'TLAXCALA'],
  ['VER', 'VERACRUZ'],
  ['YUC', 'YUCATÁN'],
  ['ZAC', 'ZACATECAS'],
]

export default states;
